<?php

include './../29-32/Automobil.class.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-04 at 22:13:43.
 */
class AutomobilTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Automobil
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Automobil('Fiat');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert (0, 0) == 0.
     *
     * @covers Automobil::add
     */
    public function testAdd()
    {
        $this->assertEquals(
                0, $this->object->add(0, 0)
        );
    }

    /**
     * Generated from @assert (0, 1) == 1.
     *
     * @covers Automobil::add
     */
    public function testAdd2()
    {
        $this->assertEquals(
                1, $this->object->add(0, 1)
        );
    }

    /**
     * Generated from @assert (1, 0) == 1.
     *
     * @covers Automobil::add
     */
    public function testAdd3()
    {
        $this->assertEquals(
                1, $this->object->add(1, 0)
        );
    }

    /**
     * Generated from @assert (1, 1) == 2.
     *
     * @covers Automobil::add
     */
    public function testAdd4()
    {
        $this->assertEquals(
                2, $this->object->add(1, 1)
        );
    }

    /**
     * Generated from @assert (1, 2) == 4.
     *
     * @covers Automobil::add
     */
    public function testAdd5()
    {
        $this->assertEquals(
                4, $this->object->add(1, 2)
        );
    }

    /**
     * @covers Automobil::get_model
     *
     * @todo   Implement testGet_model().
     */
    public function testGet_model()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Automobil::ispis
     *
     * @todo   Implement testIspis().
     */
    public function testIspis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
